# permissions for end users to view awsauthmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsauthmap-viewer-role
rules:
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmaps/status
  verbs:
  - get
