# permissions for end users to edit awsauthmaps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsauthmap-editor-role
rules:
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmaps/status
  verbs:
  - get
