# permissions for end users to view awsauthmapsnippets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsauthmapsnippet-viewer-role
rules:
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmapsnippets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmapsnippets/status
  verbs:
  - get
