# permissions for end users to edit awsauthmapsnippets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsauthmapsnippet-editor-role
rules:
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmapsnippets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.awsauth.io
  resources:
  - awsauthmapsnippets/status
  verbs:
  - get
