# permissions for end users to edit mapusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mapuser-editor-role
rules:
- apiGroups:
  - aws-auth.inovex.de
  resources:
  - mapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-auth.inovex.de
  resources:
  - mapusers/status
  verbs:
  - get
