//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 inovex GmbH

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAuthMapSnippet) DeepCopyInto(out *AwsAuthMapSnippet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAuthMapSnippet.
func (in *AwsAuthMapSnippet) DeepCopy() *AwsAuthMapSnippet {
	if in == nil {
		return nil
	}
	out := new(AwsAuthMapSnippet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsAuthMapSnippet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAuthMapSnippetList) DeepCopyInto(out *AwsAuthMapSnippetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AwsAuthMapSnippet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAuthMapSnippetList.
func (in *AwsAuthMapSnippetList) DeepCopy() *AwsAuthMapSnippetList {
	if in == nil {
		return nil
	}
	out := new(AwsAuthMapSnippetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AwsAuthMapSnippetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAuthMapSnippetSpec) DeepCopyInto(out *AwsAuthMapSnippetSpec) {
	*out = *in
	if in.MapRoles != nil {
		in, out := &in.MapRoles, &out.MapRoles
		*out = make([]MapRolesSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MapUsers != nil {
		in, out := &in.MapUsers, &out.MapUsers
		*out = make([]MapUsersSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAuthMapSnippetSpec.
func (in *AwsAuthMapSnippetSpec) DeepCopy() *AwsAuthMapSnippetSpec {
	if in == nil {
		return nil
	}
	out := new(AwsAuthMapSnippetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsAuthMapSnippetStatus) DeepCopyInto(out *AwsAuthMapSnippetStatus) {
	*out = *in
	if in.RoleArns != nil {
		in, out := &in.RoleArns, &out.RoleArns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UserArns != nil {
		in, out := &in.UserArns, &out.UserArns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsAuthMapSnippetStatus.
func (in *AwsAuthMapSnippetStatus) DeepCopy() *AwsAuthMapSnippetStatus {
	if in == nil {
		return nil
	}
	out := new(AwsAuthMapSnippetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapRolesSpec) DeepCopyInto(out *MapRolesSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapRolesSpec.
func (in *MapRolesSpec) DeepCopy() *MapRolesSpec {
	if in == nil {
		return nil
	}
	out := new(MapRolesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MapUsersSpec) DeepCopyInto(out *MapUsersSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MapUsersSpec.
func (in *MapUsersSpec) DeepCopy() *MapUsersSpec {
	if in == nil {
		return nil
	}
	out := new(MapUsersSpec)
	in.DeepCopyInto(out)
	return out
}
