name: Release Main Branch

on:
  push:
    branches:
      - main
      ignore_tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:

  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write
      packages: write

    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: setup release tools
        run: npm install -g semantic-release@21 @semantic-release/exec

      - name: Install make
        run: sudo apt-get install -y make

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push and release image
        run: npx semantic-release --branches main
        env:
          IMAGE: ${{ env.IMAGE }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

