# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and release the controller image

on:
  push:
    branches: ['release']

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write
      packages: write

    steps:

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: setup release tools
        run: npm install -g semantic-release@15 @semantic-release/exec

      - name: Install make
        run: sudo apt-get install -y make

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push and release image
        run: npx semantic-release
        env:
          IMAGE: ${{ env.IMAGE }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
