name: Test

on:
  push:
    branches:
    - '*'
  pull_request: {}

env:
  GO_VERSION: '1.17'
  KUBERNETES_VERSION: '1.19.x'

jobs:
  run-tests:
    runs-on: ubuntu-18.04

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: run tests
      run: |
        go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
        eval `setup-envtest use ${{ env.KUBERNETES_VERSION }} -p env`
        make test
